In [15]:
import numpy as np
#Array Calculations and Array Indexing
A = np.array([[1,2], [3, 4], [5, 6]])
B = np.array([[10,20], [30,40], [50,60]])
#1
print(A+B)

[[11 22]
 [33 44]
 [55 66]]


In [14]:
#2
print((np.sum(A,axis=0))/3)

[ 3.  4.]


In [21]:
#3
mean = ((np.sum(A,axis=0))/3)
diff = (A-mean)**2
std = np.sqrt((np.sum(diff, axis=0))/3)
print(std)
print(diff)
print(np.std(A,axis=0))

[ 1.63299316  1.63299316]
[[ 4.  4.]
 [ 0.  0.]
 [ 4.  4.]]
[ 1.63299316  1.63299316]


In [56]:
#4
C = np.arange(128,)
s = C[0::2]
print(np.sum(s)) 
print(np.sum(C))

4032
8128
64.0


In [57]:
#5
I = np.arange(1024) #integer array
E = I[:512]
print(E.shape)

#6
print(I)
F = I[21:42] #starts counting at 0 so should go from 22 - 42 
                #to contain value A[22] to A[42]
print(F)
print(F.shape)

(512,)
[   0    1    2 ..., 1021 1022 1023]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
(21,)


In [69]:
#7 
H = np.random.random(1024,)
D = H[I]
print(H)#to check if it's the same values
print(D)

[ 0.14922913  0.87600544  0.98773964 ...,  0.18685037  0.29558065
  0.09481232]
[ 0.14922913  0.87600544  0.98773964 ...,  0.18685037  0.29558065
  0.09481232]
[ 0.34432114  0.02027027  0.41427262  0.32025156  0.84238226]
[ 0.84238226  0.32025156  0.41427262  0.02027027  0.34432114]
[ 0.29468979  0.13403755  0.26255951  0.13443255  0.38682327  0.388407
  0.35021813  0.05195769  0.27667333  0.0432648   0.06351693  0.01693583
  0.18695852  0.29161493  0.0744896   0.25584038  0.4924872   0.49819489
  0.49624627  0.40238012  0.40217709  0.22212275  0.01140277  0.04111259
  0.39875316  0.19964537  0.38454299  0.36351332  0.02697187  0.46002789
  0.06953426  0.26974739  0.36683741  0.34501425  0.33274561  0.4352797
  0.00351932  0.1383108   0.33719067  0.22278359  0.23273185  0.09601826
  0.43892805  0.04045604  0.48913807  0.01541714  0.38987748  0.45400191
  0.26659263  0.46867461  0.15477341  0.00276492  0.20709736  0.03786745
  0.08126623  0.12381114  0.21608103  0.15647148  0.12173593  

In [70]:
#8
N = 5
J = np.random.random(N,)
print(J)
print(np.flipud(J))

#9
K = np.random.random(128,)
bool_idx = (K <= 0.5)
G = K[bool_idx]
print(G)

[ 0.89744097  0.49717223  0.19437551  0.97970483  0.79116607]
[ 0.79116607  0.97970483  0.19437551  0.49717223  0.89744097]
[ 0.04580025  0.49376496  0.36684659  0.09799843  0.23336271  0.35681387
  0.04370357  0.43029382  0.41070279  0.30015162  0.05060569  0.30514117
  0.19531919  0.39627944  0.2563444   0.49533477  0.06998165  0.1272297
  0.49820593  0.13935218  0.43829138  0.39790424  0.40291249  0.24114753
  0.48836755  0.12752927  0.03324685  0.36966532  0.30091468  0.02398792
  0.18809051  0.01399302  0.11068116  0.47936727  0.41035885  0.24553592
  0.37164501  0.25676228  0.33892714  0.12807853  0.40585541  0.3906273
  0.31487428  0.48804535  0.42183852  0.15206422  0.30802441  0.36009855
  0.36308919  0.45099934  0.16449638  0.49228005  0.07433137  0.45228135
  0.03217794  0.2054602   0.46086612  0.02283247  0.03101228  0.29053443]


In [82]:
#Views on Arrays
#1
X = np.random.random((6,3))
print(X)
i = 3
print(X[i,:])
#2
j = 2
print(X[:,j])

[[ 0.03916018  0.84806478  0.22140656]
 [ 0.69240369  0.31483446  0.75236682]
 [ 0.03306895  0.53472874  0.80518154]
 [ 0.68612409  0.64092987  0.26548494]
 [ 0.82313978  0.42356155  0.10990585]
 [ 0.07420412  0.08366612  0.61929441]]
[ 0.68612409  0.64092987  0.26548494]
[ 0.22140656  0.75236682  0.80518154  0.26548494  0.10990585  0.61929441]


In [88]:
#3 
# appears to be a bit of a mistake in the assignment 
# if you wanna know the mean of all circumferences 
# you should take the j-th column not the i-th.
# M[i] = mean X[:,j]
M = np.mean(X, axis=0)
print(M)

[ 0.39135013  0.47429759  0.46227335]


In [89]:
#4
X0 = X-M
print(X0)

[[-0.35218996  0.3737672  -0.24086679]
 [ 0.30105355 -0.15946313  0.29009347]
 [-0.35828118  0.06043116  0.34290819]
 [ 0.29477395  0.16663228 -0.19678842]
 [ 0.43178965 -0.05073604 -0.35236751]
 [-0.31714602 -0.39063147  0.15702106]]


In [92]:
#5
apple = np.array([1,3,4]) #i-rows which contain all apple data
#banana = np.array([2,5,6])#i-rows which contain all banana data
Xapple = X[apple,:]
print(X)
print(Xapple)
Ma = np.mean(Xapple,axis=0)
print(Ma) #mean of only apples

[[ 0.03916018  0.84806478  0.22140656]
 [ 0.69240369  0.31483446  0.75236682]
 [ 0.03306895  0.53472874  0.80518154]
 [ 0.68612409  0.64092987  0.26548494]
 [ 0.82313978  0.42356155  0.10990585]
 [ 0.07420412  0.08366612  0.61929441]]
[[ 0.69240369  0.31483446  0.75236682]
 [ 0.68612409  0.64092987  0.26548494]
 [ 0.82313978  0.42356155  0.10990585]]
[ 0.73388918  0.45977529  0.3759192 ]


In [105]:
#6
maxmass = np.argmax(X[:,0],axis=0)
print(X[maxmass,:])

[ 0.82313978  0.42356155  0.10990585]


In [107]:
#7
X2 = np.insert(X, 0, 1, axis=1)
print(X2)

[[ 1.          0.03916018  0.84806478  0.22140656]
 [ 1.          0.69240369  0.31483446  0.75236682]
 [ 1.          0.03306895  0.53472874  0.80518154]
 [ 1.          0.68612409  0.64092987  0.26548494]
 [ 1.          0.82313978  0.42356155  0.10990585]
 [ 1.          0.07420412  0.08366612  0.61929441]]


In [121]:
#Tricks with Arrays
#1
K = np.arange(6,)
L = K.reshape(6,1)
print(K)
print(L)
#2 
N = K.reshape(1,6)
print(N)
#3
#For an array A of shape(M,N), A[i] is the i-th row of that array. 
#The values of i can be between 0 and M-1

[0 1 2 3 4 5]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2 3 4 5]]


In [133]:
#4
P = np.arange(15)
A35 =P.reshape(3,5)
v5 = np.random.random(5,)
print(A35)
print(v5)
print(A35-v5)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0.35406348  0.35247134  0.08550517  0.75870634  0.53832258]
[[ -0.35406348   0.64752866   1.91449483   2.24129366   3.46167742]
 [  4.64593652   5.64752866   6.91449483   7.24129366   8.46167742]
 [  9.64593652  10.64752866  11.91449483  12.24129366  13.46167742]]


In [135]:
#5
v3 = np.random.random(3,)
v35 = np.tile(v3,(5,1)).T
print(v3)
print(v35)
print(A35-v35)

[ 0.85881793  0.1511718   0.56967914]
[[ 0.85881793  0.85881793  0.85881793  0.85881793  0.85881793]
 [ 0.1511718   0.1511718   0.1511718   0.1511718   0.1511718 ]
 [ 0.56967914  0.56967914  0.56967914  0.56967914  0.56967914]]
[[ -0.85881793   0.14118207   1.14118207   2.14118207   3.14118207]
 [  4.8488282    5.8488282    6.8488282    7.8488282    8.8488282 ]
 [  9.43032086  10.43032086  11.43032086  12.43032086  13.43032086]]


In [136]:
#Linear Algebra
#1
v = np.random.random(3,)
w = np.ones(3,)
print(v.dot(w))

0.90863000283


In [141]:
#2
print((A.T).dot(w))
#3 
#the shape of v.T will stay (N,)
print(np.shape(v.T))

[  9.  12.]
(3,)


In [143]:
#4
v31 = v3.reshape(3,1)
print(v3.dot(A))
#print(v31.dot(A)) needs to be resized!
print((v31.T).dot(A))


[ 4.16072901  5.74039788]
[[ 4.16072901  5.74039788]]
